### ISSUE TITLE
All peers try to connect to owner, overloading owner

### ISSUE THREAD

**Issue by holmesworcester** [TryQuiet/monorepo#736]
This came up in testing a community of 100 people. All peers tried to connect to the owner first, so the owner was going crazy with connections and dropping tons of connections. 

We should be smarter about who peers connect to initially. 

Maybe we should try random peers, or a mix of last seen and random. (3 and 3?)

**Comment by holmesworcester** [comment]
@vinkabuki will this be fixed by your latest changes?

**Comment by holmesworcester** [comment]
@vinkabuki ping!

**Comment by vinkabuki** [comment]
> @vinkabuki will this be fixed by your latest changes?

No, those changes ensured that owner is not overloaded by too many registrations

So he problem with overloading owner is not fixed, but condition for it to happen is dozens of users join at the very same time. And not only owner is at the risk.

**Comment by vinkabuki** [comment]
So the real world scenario is that there is a large group of people waiting for community to be opened/shared, like hot crypto community

**Comment by vinkabuki** [comment]
@holmesworcester
